language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y zlib1g-dev libjpeg-dev libexempi3
install: "pip install -r requirements-dev.txt"
script: nosetests tgallery_tests
